name: quiz
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-213.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  adaptive_sizer: ^0.0.4
  google_fonts: ^4.0.1
  
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  awesome_dialog: ^3.1.0
  get: ^4.6.5
  circular_countdown_timer: ^0.2.3
  vibration: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/app/
    - assets/images/web/
    - assets/json/app/
    - assets/json/web/
  #   - images/a_dot_ham.jpeg


